version: '2'

services:
  mysql:
    image: mariadb
    container_name: "passwords-mysql"
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: on-failure
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    build: ./docker/php/
    container_name: "passwords-php"
    restart: on-failure
    links:
      - mysql
    volumes:
      - ./docker/volumes/nextcloud:/var/www/html
      - ./src/:/var/www/html/custom_apps/passwords
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - SMTP_HOST=passwords-mail
      - SMTP_PORT=1025
      - MAIL_DOMAIN=passwords.app
      - MAIL_FROM_ADDRESS=noreply
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mysql:3306
    external_links:
      - "web:passwords.local"

  web:
    build: ./docker/nginx/
    container_name: "passwords-nginx"
    restart: on-failure
    ports:
      - 80:80
      - 443:443
      - 1080:1080
      - 8080:8080
    links:
      - app
    volumes_from:
      - app
    volumes:
      - ./docker/volumes/nginx:/etc/ssl/nginx/localhost

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "passwords-phpmyadmin"
    links:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: "nextcloud"
      PMA_ABSOLUTE_URI: https://localhost:8080
      PMA_HOSTS: mysql
      PMA_USER: root
      PMA_PASSWORD: nextcloud

  mail:
    image: mailhog/mailhog
    container_name: "passwords-mail"
    user: root

  iconserver:
    image: matthiasluedtke/iconserver
    container_name: "passwords-iconserver"
    environment:
      PORT: 7070

volumes:
  mysql: